---
"generator_paths": {
    0: "generator_epoch_15575_iter_77875.pt",
    1: "generator_epoch_18100_iter_90500.pt",
    2: "generator_epoch_17125_iter_85625.pt",
    3: "generator_epoch_17775_iter_88875.pt"
}

"balancing_mode": "balanced"
"bsize": 250
"evaluate_every": 1000
"save_every": 1000
"lr": 0.0001
