---
"generator_paths": {
    0: "generator_epoch_15000_iter_75001.pt",
    1: "generator_epoch_19475_iter_97375.pt",
    2: "generator_epoch_1150_iter_5750.pt",
    3: "generator_epoch_17575_iter_87875.pt"
}

"balancing_mode": "balanced"
"bsize": 250
"evaluate_every": 1000
"save_every": 1000
"lr": 0.0001
