---
"generator_paths": {
    0: "generator_epoch_19650_iter_98250.pt",
    1: "generator_epoch_19550_iter_97750.pt",
    2: "generator_epoch_850_iter_4250.pt",
    3: "generator_epoch_17725_iter_88625.pt"
}

"balancing_mode": "balanced"
"bsize": 250
"evaluate_every": 1000
"save_every": 1000
"lr": 0.0001
