---
"generator_paths": {
    0: "generator_epoch_16450_iter_82250.pt",
    1: "generator_epoch_17175_iter_85875.pt",
    2: "generator_epoch_700_iter_3500.pt",
    3: "generator_epoch_18475_iter_92375.pt"
}

"balancing_mode": "balanced"
"bsize": 250
"evaluate_every": 1000
"save_every": 1000
"lr": 0.0001
