---
"generator_paths": {
    0: "generator_epoch_7175_iter_35875.pt",
    1: "generator_epoch_15000_iter_75000.pt",
    2: "generator_epoch_4800_iter_24000.pt",
    3: "generator_epoch_8525_iter_42625.pt"
}

"balancing_mode": "balanced"
"bsize": 250
"evaluate_every": 1000
"save_every": 1000
"lr": 0.0001
